adb shell pm disable-user com.aura.oobe.samsung
adb shell pm disable-user com.sec.android.preloadinstaller
adb shell pm disable-user com.samsung.android.mapsagent
adb shell pm disable-user com.samsung.android.ardrawing
adb shell pm disable-user com.samsung.android.aremoji
adb shell pm disable-user com.sec.android.mimage.avatarstickers
adb shell pm disable-user com.samsung.android.aremojieditor
adb shell pm disable-user com.samsung.android.arzone
adb shell pm disable-user com.android.bookmarkprovider
adb shell pm disable-user com.samsung.android.livestickers
adb shell pm disable-user com.samsung.discover
adb shell pm disable-user com.samsung.android.themecenter
adb shell pm disable-user com.samsung.android.mfi
adb shell pm disable-user com.samsung.android.game.gametools
adb shell pm disable-user com.samsung.android.game.gamehome
adb shell pm disable-user com.samsung.android.game.gos
adb shell pm disable-user com.samsung.android.mobileservice
adb shell pm disable-user com.mygalaxy
adb shell pm disable-user com.samsung.android.allshare.service.mediashare
adb shell pm disable-user com.samsung.android.easylater
adb shell pm disable-user com.opera.max.oem
adb shell pm disable-user com.samsung.android.spaymini
adb shell pm disable-user com.google.android.projection.gearhead
adb shell pm disable-user com.facebook.system
adb shell pm disable-user com.facebook.appmanager
adb shell pm disable-user com.facebook.services
adb shell pm disable-user com.samsung.android.app.omcagent
adb shell pm disable-user com.samsung.android.app.sharelive
adb shell pm disable-user  com.samsung.android.dynamiclock
adb shell pm disable-user com.samsung.android.stickercenter
adb shell pm disable-user com.sec.android.app.billing
adb shell pm disable-user com.samsung.android.easysetup
adb shell pm disable-user com.samsung.android.allshare.service.mediashare
adb shell pm disable-user com.google.audio.hearing.visualization.accessibility.scribe
adb shell pm disable-user com.google.ar.core
adb shell pm disable-user com.samsung.android.themecenter
adb shell pm disable-user com.samsung.android.themestore
adb shell pm disable-user com.samsung.android.rubin.app
adb shell pm disable-user com.google.android.apps.turbo
adb shell pm disable-user com.samsung.android.ipsgeofence